name: cookbook_mobile
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  carousel_slider: ^4.2.1
  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  # Asset eklemek için assets anahtarını kullanabilirsiniz.
  assets:
    - assets/images/food_2.png
    - assets/images/food_1.png
    - assets/images/profile_1.png
    - assets/images/profile_2.png

  uses-material-design: true
